package jp.co.topgate.asada.web;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import java.io.IOException;

import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.nullValue;
import static org.junit.Assert.assertThat;

public class AppTest {
    @Test
    public void サーバースタートテスト() throws Exception {
        Server server = new Server();
        assertThat(App.controlServer(server, "1"), is("start up http server.."));
        server.endServer();
    }

    @Test
    public void 想定していない文字が入力されたテスト() throws IOException {
        Server server = new Server();
        assertThat(App.controlServer(server, "4"), is(nullValue()));
        server.endServer();
    }

    @Test(expected = NullPointerException.class)
    public void controlServerメソッドのnullチェック() throws IOException {
        Server server = new Server();
        assertThat(App.controlServer(null, null), is(nullValue()));
        server.endServer();
    }
}
